# Experiment 13
## Data Binning and Data Formatting using Python
##Name:Ayush Phale
##PRN:25070123028
###ENTC A2

In [1]:
import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000,30000,2000,8000,45000],
    'Units_Sold': [25,60,35,80,50,15]
}

df= pd.DataFrame(data)
print("Dataset")
print(df)

Dataset
      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [2]:
#Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low', 'Medium', 'High']

df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [6]:
#Data Binning
bins2 = [0,10,30,100]   #Quantity, goes till 100 as number of headphones is more than 60
labels2 = ['Less sale', 'Moderate sale', 'High sale']
df

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [7]:
#Data Formatting
#Convert Data Type
print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
dtype: object

In [8]:
#Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category
0      LAPTOP  55000        25.0           High
1      MOBILE  20000        60.0         Medium
2      TABLET  30000        35.0         Medium
3  HEADPHONES   2000        80.0            Low
4  SMARTWATCH   8000        50.0            Low
5      CAMERA  45000        15.0           High

In [9]:
#Rounding Values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category
0      LAPTOP  55000        25.0           High
1      MOBILE  20000        60.0         Medium
2      TABLET  30000        35.0         Medium
3  HEADPHONES   2000        80.0            Low
4  SMARTWATCH   8000        50.0            Low
5      CAMERA  45000        15.0           High

In [10]:
#Additional Operations
#Sort Data
sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category
3  HEADPHONES   2000        80.0            Low
4  SMARTWATCH   8000        50.0            Low
1      MOBILE  20000        60.0         Medium
2      TABLET  30000        35.0         Medium
5      CAMERA  45000        15.0           High
0      LAPTOP  55000        25.0           High

In [11]:
#Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [12]:
#Dataset: Food delivery orders
import pandas as pd
import numpy as np
data = {
    'Order ID':['01', '02', '03', '04', '05','06', '07', '08'],
    'Order_Value': [250,450,120,600,300,150,500,220],
    'Delivery_Time': [30,45,25,60,35,20,50,28],
    'Distance_km': [5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
df

  Order ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [14]:
#Binnin Order Value
bins = [0,200,400,700]
labels = ['Low Order', 'Medium Order', 'High Order']
df

  Order ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [15]:
#Binning Delivery Time
bins2 = [0,30,45,70]
labels2 = ['Fast', 'Normal', 'Slow']
df['Delivery_Speed'] = pd.cut(df['Delivery_Time'], bins=bins2, labels=labels2)
print(df)

  Order ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed
0       01          250             30            5           Fast
1       02          450             45            8         Normal
2       03          120             25            3           Fast
3       04          600             60           10           Slow
4       05          300             35            6         Normal
5       06          150             20            2           Fast
6       07          500             50            9           Slow
7       08          220             28            4           Fast

In [16]:
#Data Formatting Example
#Convert Distance to Float
df['Distance_km'] = df['Distance_km'].astype(float)
df

  Order ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed
0       01          250             30          5.0           Fast
1       02          450             45          8.0         Normal
2       03          120             25          3.0           Fast
3       04          600             60         10.0           Slow
4       05          300             35          6.0         Normal
5       06          150             20          2.0           Fast
6       07          500             50          9.0           Slow
7       08          220             28          4.0           Fast

In [17]:
#Convert Order_ID to Uppercase
df['Order_Category'] = df['Order ID'].str.upper()
df

,Order ID,Order_Value,Delivery_Time,Distance_km,Delivery_Speed,Order_Category
0,01,250,30,5.0,Fast,01
1,02,450,45,8.0,Normal,02
2,03,120,25,3.0,Fast,03
3,04,600,60,10.0,Slow,04
4,05,300,35,6.0,Normal,05
5,06,150,20,2.0,Fast,06
6,07,500,50,9.0,Slow,07
7,08,220,28,4.0,Fast,08

In [18]:
#Check Data Types
print(df.dtypes)

Order ID            object
Order_Value          int64
Delivery_Time        int64
Distance_km        float64
Delivery_Speed    category
Order_Category      object
dtype: object

In [19]:
#Unique Categories
print(df['Order_Category'].unique())
df

['01' '02' '03' '04' '05' '06' '07' '08']

,Order ID,Order_Value,Delivery_Time,Distance_km,Delivery_Speed,Order_Category
0,01,250,30,5.0,Fast,01
1,02,450,45,8.0,Normal,02
2,03,120,25,3.0,Fast,03
3,04,600,60,10.0,Slow,04
4,05,300,35,6.0,Normal,05
5,06,150,20,2.0,Fast,06
6,07,500,50,9.0,Slow,07
7,08,220,28,4.0,Fast,08

In [20]:
#Count of Categories
print(df['Order_Category'].value_counts())
df

Order_Category
01    1
02    1
03    1
04    1
05    1
06    1
07    1
08    1
Name: count, dtype: int64

,Order ID,Order_Value,Delivery_Time,Distance_km,Delivery_Speed,Order_Category
0,01,250,30,5.0,Fast,01
1,02,450,45,8.0,Normal,02
2,03,120,25,3.0,Fast,03
3,04,600,60,10.0,Slow,04
4,05,300,35,6.0,Normal,05
5,06,150,20,2.0,Fast,06
6,07,500,50,9.0,Slow,07
7,08,220,28,4.0,Fast,08

In [21]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

  Order ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed  \
2       03          120             25          3.0           Fast
5       06          150             20          2.0           Fast
7       08          220             28          4.0           Fast
0       01          250             30          5.0           Fast
4       05          300             35          6.0         Normal
1       02          450             45          8.0         Normal
6       07          500             50          9.0           Slow
3       04          600             60         10.0           Slow

  Order_Category
2             03
5             06
7             08
0             01
4             05
1             02
6             07
3             04

,Order ID,Order_Value,Delivery_Time,Distance_km,Delivery_Speed,Order_Category
0,01,250,30,5.0,Fast,01
1,02,450,45,8.0,Normal,02
2,03,120,25,3.0,Fast,03
3,04,600,60,10.0,Slow,04
4,05,300,35,6.0,Normal,05
5,06,150,20,2.0,Fast,06
6,07,500,50,9.0,Slow,07
7,08,220,28,4.0,Fast,08